### PR TITLE
Screen sharing feature UI adjustment and code refactor

### PR DESCRIPTION
**Pull request by lc-at**
In this PR, I tried to tidy things up especially the UI. As a follow-up of #9, in sum, this PR have done the following things:
- UI adjustment: added a select box for selecting a QR source and moved the auto submit checkbox to the bottom of the page
- Auto submit checkbox state is now persistent by utilizing `localStorage`
- Refactored `praesentia.js`
- I also re-organized the static files for `nimiq/qr-scanner` as it looks quite messy (this should be in another PR, but I guess that's okay)

### CODE REVIEW

**Comment by lc-at** [comment]
What do you think? @Noth3r 

Feel free to test and/or give suggestions to it.

**Comment by Noth3r** [comment]
Nice PR. It works perfectly. But I have a little suggestion to stick with the `createQrEngine` because in my pc if I create the engine manually, my chrome has lower CPU usage. How about yours?
lower_cpu

In `nimiq/qr-scanner` [docs](https://github.com/nimiq/qr-scanner/blob/master/README.md)

> As an optional third parameter a manually created QR scanner engine instance to be reused can be specified. This improves performance if you're scanning a lot of images. An engine can be manually created via QrScanner.createQrEngine(QrScanner.WORKER_PATH) (async). By default, no engine is reused for single image scanning.

**Comment by lc-at** [comment]
@Noth3r Nice catch, I didn't even know that. I can't test its performance, but we are definitely scanning a lot of images (when screen sharing) and are having performance issues. I also noticed that by not using a reusable worker, the browser requests the worker file every time it scans a frame or an image (I think this is what causes the higher CPU usage).
image

 Let me wire up the changes.

**Comment by lc-at** [comment]
Does it look good to you? @Noth3r

**Comment by Noth3r** [comment]
Yep works perfectly. Nice one @p4kl0nc4t 🎉

**Comment by lc-at** [comment]
Merged, thanks!

**Pull request merged**
